### ISSUE TITLE
How to drive servos smootly?

### ISSUE THREAD

**Issue by EmreSURK** [wedesoft/arduino-sainsmart#1]
This is great job.
Does the etc/curve.dem part do the job?
Can you explain a little bit?
Thanks.

**Comment by wedesoft** [comment]
Hi,
Thanks for your kind remark.
etc/curve.dem was just for prototyping the math for the speed profile. The actual implementation is in the *.cc files. At any time the sum of up to two speed profiles is used. The test-suite.cc file might give some more explanation.

Regards
Jan


Am 13. Mai 2018 11:53:03 GMT+01:00 schrieb "Emre ŞURK" <notifications@github.com>:
>This is great job.
>Does the etc/curve.dem part do the job?
>Can you explain a little bit?
>Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wedesoft/arduino-sainsmart/issues/1

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
